services:
  qBittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qBittorrent
    network_mode: container:GluetunVPN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8091
      - UMASK=002
    volumes:
      - /docker/qbittorrent/config:/config
      - /docker/qbittorrent/downloads:/downloads
      - /docker/qbittorrent/themes:/data/themes
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      #- "com.centurylinklabs.watchtower.monitor-only"
    restart: unless-stopped
networks:
    homelab:
        external: true