services:
  Scrypted:
    image: koush/scrypted
    container_name: Scrypted
    hostname: Scrypted #optional
    networks:
      - homelab
    ports:
      - 10443:10443
    # uncomment this and a line below as needed.
    # devices:
    # zwave usb serial device
    #   - /dev/ttyACM0:/dev/ttyACM0
    # all usb devices, such as coral tpu
    #   - /dev/bus/usb:/dev/bus/usb
    environment:
      - TZ=Europe/Paris
    volumes:
        - /docker/scrypted:/server/volume
        # modify and add the additional volume for Scrypted NVR
        # the following example would mount the /mnt/sda/video path on the host
        # to the /nvr path inside the docker container.
        # - /mnt/sda/video:/nvr
    # logging is noisy and will unnecessarily wear on flash storage.
    # scrypted has per device in memory logging that is preferred.
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "10"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      #- "com.centurylinklabs.watchtower.monitor-only"
    restart: unless-stopped
    
networks:
    homelab:
        external: true