services:
  Immich-Server:
    container_name: Immich-Server
    image: ghcr.io/immich-app/immich-server:release
    hostname: Immich-Server
    networks:
      - Network
    volumes:
      - /mnt/ZFS-NVMe/Docker/Immich/Personale:/media
      - /mnt/ZFS-NVMe/Docker/Immich/Upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris
      - DB_HOSTNAME=Immich_Postgres
      - DB_PASSWORD=fdykfuklfukfkfyuoklas56awr
      - DB_USERNAME=immich
      - DB_DATABASE_NAME=immich
      - IMMICH_TRUSTED_PROXIES=172.16.1.20
      - REDIS_HOSTNAME=Immich_Redis
      - PUID=568
      - PGID=568
    ports:
      - 2283:2283
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      disable: false
    depends_on:
      - Immich_Redis
      - Immich_Postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      #- "com.centurylinklabs.watchtower.monitor-only" 
    restart: unless-stopped
      
      
  immich-machine-learning:
    container_name: Immich-Machine-Learning
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
        # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
        # Example tag: ${IMMICH_VERSION:-release}-cuda
    hostname: immich-machine-learning
    networks:
      - Network
    volumes:
      - /mnt/ZFS-NVMe/Docker/Immich/Machine-Learning:/cache
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Paris
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      disable: false
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      #- "com.centurylinklabs.watchtower.monitor-only" 
    restart: unless-stopped

  Immich_Redis:
    container_name: Immich_Redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    hostname: Immich_Redis
    networks:
      - Network
    healthcheck:
      test: redis-cli ping || exit 1
    environment:
      - TZ=Europe/Paris
 
    restart: unless-stopped

  Immich_Postgres:
    container_name: Immich_Postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    hostname: Immich_Postgres
    networks:
      - Network
    environment:
      - TZ=Europe/Paris
      - POSTGRES_PASSWORD=fdykfuklfukfkfyuoklas56awr
      - POSTGRES_USER=immich
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
      # - DB_STORAGE_TYPE: 'HDD' # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
    volumes:
      - /mnt/ZFS-NVMe/Docker/Immich/Database:/var/lib/postgresql/data
    restart: unless-stopped
networks:
  Network:
    driver: bridge
