<?php
$CONFIG = array (
  'datadirectory' => '/data',
  'instanceid' => 'oc08hctnn1ww',
  'passwordsalt' => '404m4RSq22fea05dVBrjIqXQMFWiio',
  'secret' => '/3Q45KmCguZW/hADZvchR2cVFpsLUDSjIytG4ncmUjEaiJgW',
  'trusted_domains' => 
  array (
    0 => '172.16.1.20',
    1 => 'nextcloud.emp83.com',
  ),
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '172.16.1.20',
    'port' => '6379',
    'password' => '2JzTDEHKdP^9PeP',
  ),
  'trusted_proxies' => 
  array (
    0 => '172.16.1.20',
  ),
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    'OC\Preview\PNG',
    'OC\Preview\JPEG',
    'OC\Preview\GIF',
    'OC\Preview\BMP',
    'OC\Preview\XBitmap',
    'OC\Preview\MP3',
    'OC\Preview\TXT',
    'OC\Preview\MarkDown',
    'OC\Preview\OpenDocument',
    'OC\Preview\Krita',
    'OC\Preview\HEIC',
	'OC\Preview\Font',
	'OC\Preview\Illustrator',
	'OC\Preview\Movie',
	'OC\Preview\MSOffice2003',
	'OC\Preview\MSOffice2007',
	'OC\Preview\MSOfficeDoc',
	'OC\Preview\PDF',
	'OC\Preview\Photoshop',
	'OC\Preview\Postscript',
	'OC\Preview\StarOffice',
	'OC\Preview\SVG',
	'OC\Preview\TIFF',
	'OC\Preview\EMF',
  ),
  'dbtype' => 'mysql',
  'version' => '30.0.4.1',
  'overwrite.cli.url' => 'https://172.16.1.20:33443',
  'dbname' => 'nextcloud',
  'dbhost' => '172.16.1.20:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '6Qu3aGc$SDj3rdY%DoI1',
  'installed' => true,
  'default_phone_region' => 'FR',
  'upgrade.disable-web' => true,
  'maintenance_window_start' => 1,
  'maintenance' => false,
  'mail_domain' => 'gmail.com',
  'mail_from_address' => 'paraipanmihai',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => ' smtp.gmail.com',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'paraipanmihai@gmail.com',
  'mail_smtppassword' => 'prkngvkkjfwqecwp',
  'mail_smtpsecure' => 'ssl',
);
