services:
  Adminer:
    image: adminer:latest
    container_name: Adminer
    hostname: Adminer
    networks:
        - homelab
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Paris
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      #- "com.centurylinklabs.watchtower.monitor-only"
    restart: unless-stopped 
      
networks:
    homelab:
        external: true
