services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: Rustdesk-HBBS
    hostname: Rustdesk-HBBS
    command: hbbs
    networks:
      - homelab
    ports:
      # - "21114:21114/tcp"  # (TCP): used for web console, only available in Pro version.
      - 21115:21115  # used for the NAT type test
      - 21116:21116  # should be enabled both for TCP and UDP. is used for the ID registration and heartbeat service. 21116/TCP is used for TCP hole punching and connection service
      - 21116:21116/udp    # should be enabled both for TCP and UDP. is used for the ID registration and heartbeat service. 21116/TCP is used for TCP hole punching and connection service
      - 21118:21118  #  used to support web clients
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Paris
    volumes:
      - /mnt/ZFS-NVMe/Docker/Rustdesk:/root
    depends_on:
      - hbbr
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: Rustdesk-HBBR
    hostname: Rustdesk-HBBR
    command: hbbr
    networks:
      - homelab
    ports:
    # If you do not need web client support, the corresponding ports 21118, 21119 can be disabled.
      - 21117:21117  # used for the relay service
      - 21119:21119  # used to support web clients
    volumes:
      - /mnt/ZFS-NVMe/Docker/Rustdesk:/root
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Paris
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
    homelab:
        external: true