services:
  tailscale-nexterm:
    image: tailscale/tailscale:latest
    container_name: Tailscale-Nexterm
    hostname: Tailscale-Nexterm
    networks:
      - homelab
    ports:
      - 6989:6989
    environment:
      - TS_AUTHKEY=tskey-auth-get a key from your Tailscale account
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset
      - TS_USERSPACE=false
    volumes:
      - /docker/Nexterm/tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  nexterm:
    image: germannewsmaker/nexterm:1.0.3-OPEN-PREVIEW
    container_name: Nexterm
    network_mode: service:tailscale-nexterm
    environment:
      - TZ=Europe/Paris
      - ENCRYPTION_KEY=2f0b59cee0611e2121da31da05b1249e1dc322fd41908d1dd742c6308385a523 # Replace with your generated key
    volumes:
      - /Docker/Nexterm/config:/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    
networks:
    homelab:
        external: true
