services:
  Syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: Syncthing
    hostname: Syncthing #optional
    networks:
      - homelab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /docker/syncthing:/config
      - /mnt/truestorage/TrueNAS:/TrueNAS
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      #- "com.centurylinklabs.watchtower.monitor-only"
    restart: unless-stopped

networks:
    homelab:
        external: true