services:
  Airsonic-Advanced:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: Airsonic-Advanced
    hostname: Airsonic-Advanced
    networks:
        - homelab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /docker/airsonic-advance/config:/config
      - /mnt/ssdintern/Samba/Plex/Music:/music:ro
      - /docker/airsonic-advance/playlists:/playlists
      - docker/airsonic-advance/podcasts:/podcasts
    ports:
      - 4040:4040
    #devices:
      #- /dev/snd:/dev/snd #optional
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      #- "com.centurylinklabs.watchtower.monitor-only"
networks:
    homelab:
        external: true