services:
  Nginx-Proxy-Manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: Nginx-Proxy-Manager
    hostname: Nginx-Proxy-Manager
    networks:
        - homelab
    ports:
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      - TZ=Europe/Paris
      - DB_MYSQL_HOST=MariaDB
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm # To be configured in MariaDB
      - DB_MYSQL_PASSWORD=X23IFNmtyVM0reIXz5#f # To be configured in MariaDB
      - DB_MYSQL_NAME=npm # To be configured in MariaDB
      - INITIAL_ADMIN_EMAIL=email@mail.com
      - INITIAL_ADMIN_PASSWORD=hfoeb30hf.fh?kf
    volumes:
      - /docker/nginxproxymanager/data:/data
      - /docker/nginxproxymanager/letsencrypt:/etc/letsencrypt
      - /docker/nginxproxymanager/log:/var/log
      - /docker/nginxproxymanager/themes/:/etc/cont-init.d
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only"
    restart: unless-stopped
 
networks:
    homelab:
        external: true